name: DVC pipeline

on:
  workflow_dispatch:

#Enable docker services with dind
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          #python3 -m venv venv
          #cd venv
          #. ./bin/activate
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
      - name: Initialization
        run: |
          #cd venv
          #echo 'Now you will see dvc path'
          #which dvc || echo "DVC not found in PATH"
          #python -m site
          #pwd
          git init
          dvc init -f
