name: DVC pipeline

on:
  workflow_dispatch:

#Enable docker services with dind
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          #python3 -m venv venv
          #cd venv
          #. ./bin/activate
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
          pip uninstall -y boto3
          pip install boto3==1.35.*
          pip list | grep boto3
      - name: Initialization
        run: |
          #cd venv
          #echo 'Now you will see dvc path'
          #which dvc || echo "DVC not found in PATH"
          #python -m site
          #pwd
          git init
          dvc init -f
      - name: DVC remote configuration
        run: |
          dvc remote add yandexs3 s3://mynewbucket
          dvc remote modify yandexs3 endpointurl https://storage.yandexcloud.net
          dvc remote modify yandexs3 --local access_key_id {{secrets.YANDEX_ACCESS_KEY_ID}}
          dvc remote modify yandexs3 --local secret_access_key {{secrets.YANDEX_SECRET_ACCESS_KEY}}
          dvc remote modify yandexs3 region ru-central1
          dvc remote list
          dvc pull -r yandexs3



